---
ID: "4e6c6a38-19cc-4c85-8771-c529fce3f565"
Parent: "9f0464ac-7cf7-4ebe-9b4f-4f3df3efd4f8"
Template: "9f0464ac-7cf7-4ebe-9b4f-4f3df3efd4f8"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/ContactUs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{66FC99A4-477A-4A1F-BE22-32DF32EF9F6B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230915T060111Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "02d796a4-7d2b-4804-985e-753e2b6b7e33"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230925T063537Z
