---
ID: "8c98b440-8005-4934-a4f2-d9271f5357fd"
Parent: "fedbfbe3-1857-40d4-baa4-568c353db871"
Template: "fedbfbe3-1857-40d4-baa4-568c353db871"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/BannerCarousel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230912T071949Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ede2fd37-bb3b-45b1-a6b0-e35fbc436f0a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230912T071949Z
