---
ID: "3391f16a-00fb-4efe-a1c4-6bdb9004efc9"
Parent: "66fc99a4-477a-4a1f-be22-32df32ef9f6b"
Template: "66fc99a4-477a-4a1f-be22-32df32ef9f6b"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/ContactsData/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230922T131630Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d14b6a62-e320-4e79-be3e-d52820207ad4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230922T131630Z
