/* d70f5e590e0f49870510d9dd7dd0a6e89b82afa1
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ClientsQueryVariables = Types.Exact<{
  datasource: Types.Scalars['String'];
}>;
export type ClientsQuery = {
  __typename?: 'Query';
  fields?: {
    __typename?: 'App';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'C__AppRoute';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'C__Route';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'C__StandardTemplate';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'C__StyleguideExplanatoryComponent';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'ContentBlock';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'ExampleCustomRouteType';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'GraphQLConnectedDemo';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'GraphQLIntegratedDemo';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'JSSLayout';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'JavaScriptRendering';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'JsonRendering';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'RenderEngineType';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideComponentParams';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideComponentParamsRenderingParameters';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideContentListItemTemplate';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageCheckbox';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageContentList';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageCustom';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageDate';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageFile';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageImage';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageItemLink';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageLink';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageNumber';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageRichText';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideFieldUsageText';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideItemLinkItemTemplate';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideLayoutReuse';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideLayoutTabs';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideLayoutTabsTab';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideMultilingual';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideRouteFields';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideSection';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideSitecoreContext';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'StyleguideTracking';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | {
    __typename?: 'UnknownItem';
    ClientsList?: {
      __typename?: 'CheckboxField';
      data: any;
    } | {
      __typename?: 'DateField';
      data: any;
    } | {
      __typename?: 'ImageField';
      data: any;
    } | {
      __typename?: 'IntegerField';
      data: any;
    } | {
      __typename?: 'LinkField';
      data: any;
    } | {
      __typename?: 'LookupField';
      data: any;
    } | {
      __typename?: 'MultilistField';
      data: any;
    } | {
      __typename?: 'NameValueListField';
      data: any;
    } | {
      __typename?: 'NumberField';
      data: any;
    } | {
      __typename?: 'RichTextField';
      data: any;
    } | {
      __typename?: 'TextField';
      data: any;
    } | null;
    fields: Array<{
      __typename?: 'CheckboxField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'DateField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'ImageField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'IntegerField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LinkField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'LookupField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'MultilistField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NameValueListField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'NumberField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'RichTextField';
      name: string;
      value?: string | null;
    } | {
      __typename?: 'TextField';
      name: string;
      value?: string | null;
    } | null>;
  } | null;
};
export declare const ClientsDocument: DocumentNode<ClientsQuery, Types.Exact<{
  datasource: Types.Scalars['String'];
}>>;