/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/no-namespace */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type About = { 
        fields?: { 
            /**
            * Represents the AboutDescription field (8a91480a-c088-4642-a0de-07ca64fcac77).
            */
            AboutDescription: Field<string>;

            /**
            * Represents the AboutImage field (f9b0b1e0-dd49-4853-8507-0827c6de26d3).
            */
            AboutImage: ImageField;

            /**
            * Represents the AboutReadMoreCTA field (288a4e26-cb7f-43fe-845c-33161de588a9).
            */
            AboutReadMoreCTA: LinkField;

            /**
            * Represents the AboutReadMoreCTAText field (39f2e9a0-53d8-4a96-a026-e0790071b84c).
            */
            AboutReadMoreCTAText: Field<string>;

            /**
            * Represents the AboutTitle field (545e682e-c78f-41f4-8e1f-703daca3cee3).
            */
            AboutTitle: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Banner = { 
        fields?: { 
            /**
            * Represents the BannerBackgroundImage field (2210ecd7-daa4-445b-b03f-d437ef669b6f).
            */
            BannerBackgroundImage: ImageField;

            /**
            * Represents the BannerCarousels field (ec38ec93-239c-4aa5-b168-882446e33bc6).
            */
            BannerCarousels: Sitecore.Override.ItemEx[];
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type BannerCarousel = { 
        fields?: { 
            /**
            * Represents the BannerCarouselDescription field (65ad9d67-2e22-46dc-b2a2-517c759d6f24).
            */
            BannerCarouselDescription: Field<string>;

            /**
            * Represents the BannerCarouselQuoteCTA field (9fca51b8-6561-4c95-b491-1e25afac0b7d).
            */
            BannerCarouselQuoteCTA: LinkField;

            /**
            * Represents the BannerCarouselQuoteCTAText field (6ea7e25f-18f4-4d1a-a4d5-be4a514d2da5).
            */
            BannerCarouselQuoteCTAText: Field<string>;

            /**
            * Represents the BannerCarouselReadMoreCTA field (9c8c63f1-0768-4105-af4f-cac9f6b6f572).
            */
            BannerCarouselReadMoreCTA: LinkField;

            /**
            * Represents the BannerCarouselReadMoreCTAText field (9accfa6a-bc75-41bf-88a9-fbff337dc05e).
            */
            BannerCarouselReadMoreCTAText: Field<string>;

            /**
            * Represents the BannerCarouselTitle field (936721e7-8684-4a43-bfb7-1cd114d3c28d).
            */
            BannerCarouselTitle: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Client = { 
        fields?: { 
            /**
            * Represents the ClientDescription field (98aae187-a2c7-42e8-bdfb-1995c195ccd0).
            */
            ClientDescription: Field<string>;

            /**
            * Represents the ClientImage field (1d0011cc-d776-4c24-91ab-6db9b9c1f56b).
            */
            ClientImage: ImageField;

            /**
            * Represents the ClientName field (617b36f5-206e-4861-85f8-05e59eabaaa2).
            */
            ClientName: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Clients = { 
        fields?: { 
            /**
            * Represents the ClientsHeading field (781fab61-554e-4a9a-833e-03f9ba98280e).
            */
            ClientsHeading: Field<string>;

            /**
            * Represents the ClientsList field (460d6909-d8a9-4adb-868d-f40e1059482a).
            */
            ClientsList: Sitecore.Override.ItemEx[];
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type ContactUs = { 
        fields?: { 
            /**
            * Represents the ContactUsBackgroundImage field (622c9875-1d36-4ee9-aee6-e763086bc24d).
            */
            ContactUsBackgroundImage: ImageField;

            /**
            * Represents the ContactUsCTA field (4036ba0d-86e7-4009-ac87-e267f631adba).
            */
            ContactUsCTA: LinkField;

            /**
            * Represents the ContactUsCTAText field (1df28624-9353-46e9-8aa3-e5cd1feccb99).
            */
            ContactUsCTAText: Field<string>;

            /**
            * Represents the ContactUsEmailPlaceholder field (a7afc2db-2869-4546-8542-10f469713c15).
            */
            ContactUsEmailPlaceholder: Field<string>;

            /**
            * Represents the ContactUsHeading field (e5c253c6-c0d2-4610-a40b-6eedca5f4185).
            */
            ContactUsHeading: Field<string>;

            /**
            * Represents the ContactUsMessagePlaceholder field (530493d4-7fe9-40c7-8c53-518e69f16ed8).
            */
            ContactUsMessagePlaceholder: Field<string>;

            /**
            * Represents the ContactUsNamePlaceholder field (ac103b45-d94a-47eb-93fd-2bc00ee41dfc).
            */
            ContactUsNamePlaceholder: Field<string>;

            /**
            * Represents the ContactUsNumberPlaceholder field (22b9c00d-18ad-4047-af59-b1f2f41f4e47).
            */
            ContactUsNumberPlaceholder: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type ContactsData = { 
        fields?: { 
            /**
            * Represents the Email field (d46b3432-2abb-42f4-bba3-b4b45df8129f).
            */
            Email: Field<string>;

            /**
            * Represents the Message field (0dcf46fd-1638-463c-9ddd-7954b7c9442a).
            */
            Message: Field<string>;

            /**
            * Represents the Name field (f74136b9-940c-4a55-bf3f-e14866360844).
            */
            Name: Field<string>;

            /**
            * Represents the PhoneNumber field (1bd61a9d-0868-4e2a-baa1-5328331e9cef).
            */
            PhoneNumber: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Guard = { 
        fields?: { 
            /**
            * Represents the GuardDesignation field (58b22c1f-4f99-4fe2-b031-0961ccdc3266).
            */
            GuardDesignation: Field<string>;

            /**
            * Represents the GuardImage field (7abee608-b53e-4b2b-bd6b-9ba795231180).
            */
            GuardImage: ImageField;

            /**
            * Represents the GuardName field (89c97fc4-a31f-4963-8154-84472f40425f).
            */
            GuardName: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Guards = { 
        fields?: { 
            /**
            * Represents the GuardsCTA field (a4d660dc-4da6-4360-9f3e-2c0cae5250e6).
            */
            GuardsCTA: LinkField;

            /**
            * Represents the GuardsCTAText field (c45b7a2d-020d-4b46-ae27-57f049261339).
            */
            GuardsCTAText: Field<string>;

            /**
            * Represents the GuardsDescription field (50a7c05a-111b-473b-bac6-7da2536eedbc).
            */
            GuardsDescription: Field<string>;

            /**
            * Represents the GuardsHeading field (cb190fa9-bd9e-422b-826a-19cee88341a0).
            */
            GuardsHeading: Field<string>;

            /**
            * Represents the GuardsList field (d0a169da-9a94-4a7d-b04e-a6985212b4c5).
            */
            GuardsList: Sitecore.Override.ItemEx[];
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.RenderingParameters.Fields {
    export type PageContent = { 
        fields?: {  
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Promo = { 
        fields?: { 
            /**
            * Represents the Image field (f94b9858-c439-4291-863b-757b536c8b65).
            */
            PromoIcon: ImageField;

            /**
            * Represents the Image 2 field (739c6cc2-0031-463d-9599-13478fd50ee3).
            */
            PromoIcon2: ImageField;

            /**
            * Represents the Link field (ef24bed2-46ab-4d53-ad1a-1019935a4e89).
            */
            PromoLink: LinkField;

            /**
            * Represents the Text field (28079f3a-896b-4273-be5f-59d0ebb7cd7d).
            */
            PromoText: Field<string>;

            /**
            * Represents the Text 2 field (1f66862d-a5e3-405f-8e3e-b787b4c39b12).
            */
            PromoText2: Field<string>;

            /**
            * Represents the Text 3 field (c6e604c3-5371-4e67-83df-a09a5ea66249).
            */
            PromoText3: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.RenderingParameters.Fields {
    export type Promo = { 
        fields?: {  
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type PromoFolder = { 
        fields?: {  
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.RenderingParameters.Fields {
    export type RichText = { 
        fields?: {  
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Service = { 
        fields?: { 
            /**
            * Represents the ServiceCTA field (76472946-e2a1-42ad-8802-a242465ca91e).
            */
            ServiceCTA: LinkField;

            /**
            * Represents the ServiceCTAText field (0309b551-d5c8-425e-926d-f0fcb53a5063).
            */
            ServiceCTAText: Field<string>;

            /**
            * Represents the ServiceDescription field (587ea32e-87c6-4e21-8a3e-bc98177cdf82).
            */
            ServiceDescription: Field<string>;

            /**
            * Represents the ServiceLogo field (27ee4218-5851-4b31-8094-99c845d40fa4).
            */
            ServiceLogo: ImageField;

            /**
            * Represents the ServiceTitle field (ee23cfcb-02a6-4f10-92b7-87c5c01d570f).
            */
            ServiceTitle: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Services = { 
        fields?: { 
            /**
            * Represents the ServicesHeading field (49c8df06-3d0b-4bda-9c32-af659fb445db).
            */
            ServicesHeading: Field<string>;

            /**
            * Represents the ServicesList field (ae41e359-9e2d-4791-99bb-da07ee44fd9f).
            */
            ServicesList: Sitecore.Override.ItemEx[];
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type Text = { 
        fields?: { 
            /**
            * Represents the Text field (729034fc-24f3-40b7-8fa4-fb49d7de20dd).
            */
            Texts: Field<string>;
 
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.Fields {
    export type TextFolder = { 
        fields?: {  
        }
 }; 
}

export namespace feature-templates.Sitecore.templates.JssExperienceAccelerator.PageContent.RenderingParameters.Fields {
    export type Title = { 
        fields?: {  
        }
 }; 
}


